### ISSUE TITLE
Small error in webpack.config.js

### ISSUE THREAD

**Issue by dave-grix** [GrantBartlett/react-typescript-webpack-starter#1]
Webpack config has a small error that stops compile when freshly pulled.

```entry: {
        app: ['./src/app.ts'],
        vendor: ['react', 'react-dom']
    },
```

should be

```entry: {
        app: ['./src/App.ts'],
        vendor: ['react', 'react-dom']
    },
```

**Comment by dave-grix** [comment]
PR Created https://github.com/GrantBartlett/react-typescript-webpack-starter/pull/2

**Comment by GrantBartlett** [comment]
https://github.com/GrantBartlett/react-typescript-webpack-starter/pull/2
