### ISSUE TITLE
Functional components

### ISSUE THREAD

**Issue by chapster11** [GrantBartlett/react-typescript-webpack-starter#5]
I like the simplicity of this starter kit but would like to change to functional components instead of class component. I tried changing the components from class components to functional components but it seems to not render the same. 

Example: App.ts

const Component = () => <div>HELLO<div>;

ReactDOM.render(<Component />, document.getElementById("app"));

**Comment by GrantBartlett** [comment]
Hi @chapster11  - just added a functional branch you can try out. https://github.com/GrantBartlett/react-typescript-webpack-starter/tree/functional

**Comment by GrantBartlett** [comment]
Closing since there's now a branch for this if needed. Any issues feel free to re-open.
